# Generated by Django 3.0.2 on 2020-02-19 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20200218_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgroup',
            name='group',
            field=models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postsgroup', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='postgroup',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postgroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postsgroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
